[tool.poetry]
name = "project_2-zagrebina-m26-555"
version = "0.1.0"
description = "Примитивная база данных с консольным интерфейсом: таблицы, CRUD-операции, хранение в JSON"
authors = ["Victoria Zagrebina <seventeen.joker@gmail.com>"]
readme = "README.md"
packages = [
    { include = "primitive_db", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.12"
prompt = "^0.4.1"
prettytable = "^3.10"

[tool.poetry.group.dev.dependencies]
ruff = "^0.16.9"

[tool.poetry.scripts]
database = "primitive_db.main:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 88
target-version = "py312"
exclude = ["venv", ".venv", "dist", "__pycache__"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []
